export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const FETCH_DETAIL_PANEL_DATA = 'FETCH_DETAIL_PANEL_DATA';
export const UPDATE_PATH = 'UPDATE_PATH';
export const RESET_ORGANISATIONS = 'RESET_ORGANISATIONS';
export const SET_FORM_OPEN_BY_PANEL_ID = 'SET_FORM_OPEN_BY_PANEL_ID';
