export const STORE_FORM_DATA = 'STORE_FORM_DATA';
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const FETCH_DETAIL_PANEL_DATA = 'FETCH_DETAIL_PANEL_DATA';
export const UPDATE_PATH = 'UPDATE_PATH';
export const STORE_SECTION_INFO = 'STORE_SECTION_INFO';
