###############################################################################
## Stages
################################################################################
stages:
  - build
  - deploy_acc
  #- deploy_prod

################################################################################
## Variables
################################################################################
variables:
  BUILD_CONTAINER: psybizz-registry.githost.io/containers/builder:stable

cache:
  paths:
    - vendor/
    - node_modules/

################################################################################
## Templates
################################################################################
## Deploy and run tests
.test_and_build:
  before_script: &test_and_build
    - yarn install --ignore-platform --no-progress --non-interactive
    - yarn run deploy

## Shared build job config
.build_stage: &build_stage
  stage: build
  image: ${BUILD_CONTAINER}
  before_script: *test_and_build
  script:
    - echo "build stage"
  cache:
    paths:
      - node_modules/

## Deploy acceptance using Rancher
.deploy_acc_s3: &deploy_acc_s3
  image: ${BUILD_CONTAINER}
#  napp/docker-aws-cli
  services:
    - docker:dind
  before_script: *test_and_build
  script:
#    - yarn install --ignore-platform --no-progress --non-interactive
#    - yarn run deploy
    - docker run -v /builds/neon/frontend2/:/opt/webapp napp/docker-aws-cli aws s3 cp /opt/webapp/index.html ${AWS_BUCKET_ACCEPTANCE}
    - docker run -v /builds/neon/frontend2/:/opt/webapp napp/docker-aws-cli aws s3 cp /opt/webapp/service-worker.js ${AWS_BUCKET_ACCEPTANCE}
    - docker run -v /builds/neon/frontend2/:/opt/webapp napp/docker-aws-cli aws s3 cp /opt/webapp/web/ ${AWS_BUCKET_ACCEPTANCE} --recursive
#    - aws s3 cp index.html ${AWS_BUCKET_ACCEPTANCE}
#    - aws s3 cp service-worker.js ${AWS_BUCKET_ACCEPTANCE}
#    - aws s3 cp ./web/ ${AWS_BUCKET_ACCEPTANCE} --recursive
  only:
    - deploy-acceptance

## Deploy production using Rancher
#.deploy_prod_s3: &deploy_prod_s3
#  image: napp/docker-aws-cli
#  script:
#    - aws s3 cp index.html ${AWS_BUCKET_PRODUCTION}
#    - aws s3 cp service-worker.js ${AWS_BUCKET_PRODUCTION}
#    - aws s3 cp ./web/ ${AWS_BUCKET_PRODUCTION} --recursive
#  only:
#    - master

################################################################################
## Building & Testing
################################################################################

build:
  <<: *build_stage

################################################################################
## Deploys
################################################################################

## Deploy to Acceptance
deploy_acc:
  <<: *deploy_acc_s3
  stage: deploy_acc

## Deploy to Production
#deploy_acc:
#  <<: *deploy_stage_s3
#  stage: deploy_acc
