###############################################################################
## Stages
################################################################################
stages:
  - build
  - deploy_acc
  #- deploy_prod

################################################################################
## Variables
################################################################################
variables:
  BUILD_CONTAINER: psybizz-registry.githost.io/containers/builder:stable

cache:
  paths:
    - vendor/

################################################################################
## Templates
################################################################################
## Deploy and run tests
.test_and_build:
  before_script: &test_and_build
#    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - yarn install --ignore-platform --no-progress --non-interactive
#    - yarn run deploy

## Shared build job config
.build_stage: &build_stage
  stage: build
  image: ${BUILD_CONTAINER}
#  services:
#    - docker:dind
  before_script: *test_and_build
  script:
    - echo "build stage"
  cache:
    paths:
      - node_modules/

## Deploy project using Rancher
.deploy_stage_s3: &deploy_stage_s3
  image: napp/docker-aws-cli
  script:
    - aws s3 cp index.html ${AWS_BUCKET_ACCEPTANCE}
#    - aws s3 cp ./web ${AWS_BUCKET}
#  only:
#    - master

################################################################################
## Building & Testing
################################################################################

build:
  <<: *build_stage

################################################################################
## Deploys
################################################################################

## Deploy to Acceptance
deploy_acc:
  <<: *deploy_stage_s3
  stage: deploy_acc
