###############################################################################
## Stages
################################################################################
stages:
  - build
  - deploy_acc
  #- deploy_prod

################################################################################
## Variables
################################################################################
variables:
  BUILD_CONTAINER: psybizz-registry.githost.io/containers/builder:stable

################################################################################
## Templates
################################################################################
## Deploy and run tests
## Shared build job config
.build_stage: &build_stage
  stage: build
  image: ${BUILD_CONTAINER}
  script:
    - echo "build stage"
    - yarn install --ignore-platform --no-progress --non-interactive
    - yarn run deploy
  cache:
    paths:
      - node_modules/

## Deploy acceptance using Rancher
.deploy_acc_stage: &deploy_acc_stage
  image: napp/docker-aws-cli
  script:
    - aws s3 cp index.html ${AWS_BUCKET_ACCEPTANCE}
    - aws s3 cp service-worker.js ${AWS_BUCKET_ACCEPTANCE}
    - aws s3 cp web ${AWS_BUCKET_ACCEPTANCE}/web --recursive
  only:
    - deploy-acceptance
    #- master
  dependencies:
    - build

#.deploy_acc_s3: &deploy_acc_s3
#  image: ${BUILD_CONTAINER}
#  services:
#    - docker:dind
#  before_script: *test_and_build
#  script:
#    - docker run
#      -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
#      -e "AWS_REGION=${AWS_REGION}"
#      -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
#      -v /builds/neon/frontend2/:/opt/webapp/
#      napp/docker-aws-cli aws s3 cp /opt/webapp/index.html ${AWS_BUCKET_ACCEPTANCE}
#    - docker run
#      -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
#      -e "AWS_REGION=${AWS_REGION}"
#      -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
#      -v /builds/neon/frontend2/:/opt/webapp/
#      napp/docker-aws-cli aws s3 cp /opt/webapp/service-worker.js ${AWS_BUCKET_ACCEPTANCE}
#    - docker run
#      -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
#      -e "AWS_REGION=${AWS_REGION}"
#      -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
#      -v /builds/neon/frontend2/:/opt/webapp/
#      napp/docker-aws-cli aws s3 cp /opt/webapp/web ${AWS_BUCKET_ACCEPTANCE}/web --recursive
#  only:
#    - deploy-acceptance
#    #- master

## Deploy production using Rancher TODO: copy from acceptance
#.deploy_prod_s3: &deploy_prod_s3
#  image: napp/docker-aws-cli
#  script:
#    - aws s3 cp index.html ${AWS_BUCKET_PRODUCTION}
#    - aws s3 cp service-worker.js ${AWS_BUCKET_PRODUCTION}
#    - aws s3 cp ./web/ ${AWS_BUCKET_PRODUCTION} --recursive
#  only:
#    - master

################################################################################
## Building & Testing
################################################################################

build:
  <<: *build_stage
  artifacts:
    paths:
      - vendor/
#      - node_modules/
      - web/

################################################################################
## Deploys
################################################################################

## Deploy to Acceptance
deploy_acc:
  <<: *deploy_acc_stage
  stage: deploy_acc

## Deploy to Production
#deploy_prod:
#  <<: *deploy_prod_s3
#  stage: deploy_prod
