###############################################################################
## Stages
################################################################################
stages:
  - build
  - deploy_acc
  #- deploy_prod

################################################################################
## Variables
################################################################################
variables:
  BUILD_CONTAINER: psybizz-registry.githost.io/containers/builder:aws_cli_test

################################################################################
## Templates
################################################################################
## Deploy and run tests
## Shared build job config
.build_acc_stage: &build_acc_stage
  stage: build
  image: ${BUILD_CONTAINER}
  script:
    - echo "build stage"
    - yarn install --ignore-platform --no-progress --non-interactive
    - yarn run build:acc
  cache:
    paths:
      - node_modules/

## Deploy acceptance using aws cli
.deploy_acc_stage: &deploy_acc_stage
  <<: *build_acc_stage
  script:
    - aws s3 cp index.html ${AWS_BUCKET_ACCEPTANCE}
    - aws s3 cp service-worker.js ${AWS_BUCKET_ACCEPTANCE}
    - aws s3 sync web ${AWS_BUCKET_ACCEPTANCE}/web --delete
  only:
    - deploy-acceptance
#    - master

## Deploy production using aws cli
#.deploy_acc_stage: &deploy_prod_stage
#  image: napp/docker-aws-cli
#  script:
#    - aws s3 cp index.html ${AWS_BUCKET_PRODUCTION}
#    - aws s3 cp service-worker.js ${AWS_BUCKET_PRODUCTION}
#    - aws s3 sync web ${AWS_BUCKET_PRODUCTION}/web --delete
#  only:
#    - master
#  dependencies:
#    - build

################################################################################
## Building & Testing
################################################################################

#build: TODO: Renable, as a prod build
#  <<: *build_stage

################################################################################
## Deploys
################################################################################

## Deploy to Acceptance
deploy_acc:
  <<: *deploy_acc_stage
  stage: deploy_acc

## Deploy to Production
#deploy_prod:
#  <<: *deploy_prod_stage
#  stage: deploy_prod
