const UserRoles = {
    ROLE_APPLICATION_MANAGERS: 'ROLE_APPLICATION_MANAGERS',
    ROLE_CONSULTANTS: 'ROLE_CONSULTANTS',
    ROLE_BEDRIJFSBUREAU: 'ROLE_BEDRIJFSBUREAU',
    ROLE_BACKOFFICE: 'ROLE_BACKOFFICE',
    ROLE_CLIENT_CENTER: 'ROLE_CLIENT_CENTER',
    ROLE_ASSESSMENT_TEAM: 'ROLE_ASSESSMENT_TEAM',
    ROLE_ASSESSORS: 'ROLE_ASSESSORS',
    ROLE_PARTICIPANT: 'ROLE_PARTICIPANT'
};

export default UserRoles;
