export const GET_REPORT = 'GET_REPORT';
export const RESET_REPORT = 'RESET_REPORT';
export const UPDATE_TEXT_FIELD = 'UPDATE_TEXT_FIELD';
export const UPDATE_COMPETENCY_SCORE = 'UPDATE_COMPETENCY_SCORE';
export const UPDATE_REPORT_GENERATION_STATUS = 'UPDATE_REPORT_GENERATION_STATUS';
